name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PUSH_USERNAME }}
          password: ${{ secrets.PUSH_TOKEN }}
    
      - name: Extract commit hash 
        id: vars
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cyberhotline/itflow:latest
            ghcr.io/cyberhotline/itflow:${{steps.vars.outputs.commit_hash}}